# Generated by Django 5.2 on 2025-05-01 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 9, 54, 31, 799700, tzinfo=datetime.timezone.utc)),
        ),
    ]
